name: Go
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - uses: actions/checkout@v2

      - run: go mod download

      - run: go mod verify

      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

      - run: $(go env GOPATH)/bin/golangci-lint run ./...

      - run: go test ./...

      - run: go build cmd/things/main.go
